.type total
.type height
.type weight
.type birth_date
.type people_id
.type snatch
.type clean_jerk
.type name
.type body_builder_id
.type birth_place

.decl body_builder(v0: body_builder_id, v1: people_id, v2: snatch, v3: clean_jerk, v4: total)
.input body_builder
.decl people(v0: people_id, v1: name, v2: height, v3: weight, v4: birth_date, v5: birth_place)
.input people
// select t2.weight from body_builder as t1 join people as t2 on t1.people_id  =  t2.people_id where t1.snatch  >  140 or t2.height  >  200;
.ord snatch
.ord height

.decl op269(v0: weight)
.output op269
